---
apiVersion: v1
kind: Namespace
metadata:
  name: konveyor-tackle
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: konveyor-tackle
spec:
  targetNamespaces:
  - konveyor-tackle
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: konveyor-operator
  namespace: konveyor-tackle
spec:
  channel: konveyor-0.9
  name: konveyor-operator
  source: operatorhubio-catalog
  sourceNamespace: olm